Add all methods, implement them for standard contract object
Cerebellum-Network/cere-ddc-sdk-go pull request #60
Opened 2023-07-18 18:42 UTC by CereVGello

Add placeholders for a mock and a contract with cache objects TODO: implement for mock and contract with cache
Check events and errors
Add test coverage

2023-08-01 21:54 UTC, yahortsaryk requested changes

2023-08-01 21:54 UTC, yahortsaryk commented on contract/pkg/cache/ddc_bucket_contract_cache.go
> +	if clusterId == 0 {
It is possible to have `0` id for the cluster, currently cluster_id is `u32` type, so the very first cluster will have id that equals to `0`

2023-08-01 21:54 UTC, yahortsaryk commented on contract/pkg/cache/ddc_bucket_contract_cache.go
> +	if clusterId == 0 {
The same here, it is possible to have cluster with id=`0`

2023-10-17 10:40 UTC, idmitriev approved these changes

2023-10-17 10:40 UTC, yahortsaryk approved these changes

2023-10-17 10:40 UTC, merged